Added isDisplayed.
LambdaTest/python-selenium-sample pull request #3
Opened 2022-04-18 14:13 UTC by Saurabh-LT

2022-04-21 07:07 UTC, sururocks commented on lambdatest.py
> +        print("Search button is displayed " + str(search.is_displayed()))
does it gonna fail?
it should fail if that command is not working.
add assert.

2022-04-21 07:07 UTC, sururocks commented on lambdatest.py
> +            "browserName": "firefox",
you supposed to add code for selenium 4

2022-04-21 07:08 UTC, sururocks requested changes
change requested

2022-05-10 05:46 UTC, Saurabh-LT commented on lambdatest.py
> +            "browserName": "firefox",
It's already added

2022-05-10 05:59 UTC, Saurabh-LT commented on lambdatest.py
> +            "browserName": "firefox",
line number 20

2022-05-10 06:28 UTC, closed without merging